[package]
name = "misc"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
doctest = false
name = "misc"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
# macro dependencies
extend = { workspace = true }

# utility dependencies

